-- treesitter extras

return {
    ensure_installed = {
        "bash",
        "css",
        "csv",
        "diff",
        "dockerfile",
        "editorconfig",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "graphql",
        "html",
        "ini",
        "javascript",
        "jsdoc",
        "json",
        "json5",
        "jsonc",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "markdown_inline",
        "nginx",
        "php",
        "php_only",
        "phpdoc",
        "regex",
        "scss",
        "sql",
        "tsx",
        "typescript",
        "twig",
        "vim",
        "vue",
        "xml",
        "yaml",
    },
}
