return {
    "glepnir/dashboard-nvim",
    event = "VimEnter",
    config = function()
        require("dashboard").setup({
            theme = "doom",
            config = {
                header = {
                    "", "", "", "", "", "", "", "",
                    "ooooo      ooo oooooooooooo   .oooooo.   oooooo     oooo ooooo ooo        ooooo",
                    "`888b.     `8' `888'     `8  d8P'  `Y8b   `888.     .8'  `888' `88.       .888'",
                    " 8 `88b.    8   888         888      888   `888.   .8'    888   888b     d'888 ",
                    " 8   `88b.  8   888oooo8    888      888    `888. .8'     888   8 Y88. .P  888 ",
                    " 8     `88b.8   888    '    888      888     `888.8'      888   8  `888'   888 ",
                    " 8       `888   888       o `88b    d88'      `888'       888   8    Y     888 ",
                    "o8o        `8  o888ooooood8  `Y8bood8P'        `8'       o888o o8o        o888o",
                    "", "", "", "", "", "",
                },
                center = {
                    {
                        icon = "󰙅   ",
                        icon_hl = "Title",
                        desc = "Open tree",
                        desc_hl = "String",
                        key = "e",
                        key_hl = "Number",
                        action = ":Neotree float",
                    },
                    {
                        icon = "󰈞   ",
                        icon_hl = "Title",
                        desc = "Find files",
                        desc_hl = "String",
                        key = "f",
                        key_hl = "Number",
                        action = ":Telescope find_files",
                    },
                    {
                        icon = "   ",
                        icon_hl = "Title",
                        desc = "Find text",
                        desc_hl = "String",
                        key = "w",
                        key_hl = "Number",
                        action = ":Telescope live_grep",
                    },
                    {
                        icon = "   ",
                        icon_hl = "Title",
                        desc = "Git Braches",
                        desc_hl = "String",
                        key = "b",
                        key_hl = "Number",
                        action = ":Telescope git_branches",
                    },
                    {
                        icon = "   ",
                        icon_hl = "Title",
                        desc = "Lazy",
                        desc_hl = "String",
                        key = "l",
                        key_hl = "Number",
                        action = ":Lazy",
                    },
                    {
                        icon = "󰈆   ",
                        icon_hl = "Title",
                        desc = "Quit",
                        desc_hl = "String",
                        key = "q",
                        key_hl = "Number",
                        action = ":q",
                    },
                },
            },
        })
    end,
}
