require("nvim-treesitter.configs").setup({
    ensure_installed = {
        "bash",
        "css",
        "html",
        "ini",
        "javascript",
        "jsdoc",
        "json",
        "json5",
        "lua",
        "luadoc",
        "markdown",
        "markdown_inline",
        "nginx",
        "php",
        "php_only",
        "phpdoc",
        "query",
        "regex",
        "scss",
        "sql",
        "tsx",
        "twig",
        "typescript",
        "vim",
        "vimdoc",
        "vue",
        "xml",
        "yaml",
    },

    sync_install = true,
    auto_install = true,

    highlight = {
        enable = true,
    },
})

